// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmGkabBB0i-8rX2qNwcGP3DqhJF1EVmQ',
    appId: '1:278766114098:web:4eb2b7c9845540a412f32b',
    messagingSenderId: '278766114098',
    projectId: 'donde-vamos-19c1a',
    authDomain: 'donde-vamos-19c1a.firebaseapp.com',
    storageBucket: 'donde-vamos-19c1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfepv23Dbkil4na2XWT0IvoJUufO1q6U',
    appId: '1:278766114098:android:a9d2bddf193979c312f32b',
    messagingSenderId: '278766114098',
    projectId: 'donde-vamos-19c1a',
    storageBucket: 'donde-vamos-19c1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxpsDH_9H-a1s9WRrlpgwY8BaGHICX2E',
    appId: '1:278766114098:ios:9c117aaa0ca640f812f32b',
    messagingSenderId: '278766114098',
    projectId: 'donde-vamos-19c1a',
    storageBucket: 'donde-vamos-19c1a.appspot.com',
    androidClientId: '278766114098-o1q3qq5h0pcc3na0jcddt3pj1s1flcla.apps.googleusercontent.com',
    iosClientId: '278766114098-a6f5en3ll2mhkq5747vk34cv1di92j71.apps.googleusercontent.com',
    iosBundleId: 'com.example.dondeVamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqxpsDH_9H-a1s9WRrlpgwY8BaGHICX2E',
    appId: '1:278766114098:ios:9c117aaa0ca640f812f32b',
    messagingSenderId: '278766114098',
    projectId: 'donde-vamos-19c1a',
    storageBucket: 'donde-vamos-19c1a.appspot.com',
    androidClientId: '278766114098-o1q3qq5h0pcc3na0jcddt3pj1s1flcla.apps.googleusercontent.com',
    iosClientId: '278766114098-a6f5en3ll2mhkq5747vk34cv1di92j71.apps.googleusercontent.com',
    iosBundleId: 'com.example.dondeVamos',
  );
}
